# Preprocessing Discover Graph text data

In [5]:
from neo4j import GraphDatabase, basic_auth
import pandas as pd
import numpy as np
import os
import json
import spacy
import collections
nlp = spacy.load('en_core_web_sm')

In [6]:
driver = GraphDatabase.driver( "bolt://localhost:7687",  auth=basic_auth("neo4j", "nindoo123"))

In [7]:
pulling_query = """\
            MATCH (a:Text)
            RETURN ID(a) AS ID, a.description AS description
            """
with driver.session() as sess:
    result = sess.run(pulling_query)
    blogs_desc = pd.DataFrame([dict(row) for row in result])
print("Shape",blogs_desc.shape)
blogs_desc.head()

Shape (280, 2)

    ID                                        description
0  360  And not just in school, but at home Continue r...
1  380  I have always wondered if a Design system shou...
2  381  Learn the basic concepts behind the most commo...
3  382  Maybe they should all meet the same fate Conti...
4  383  “The current protests are not simply about rac...

In [8]:
pulling_query = """\
            MATCH (a:INTEREST)
            RETURN ID(a) AS ID, a.description AS description
            """
with driver.session() as sess:
    result = sess.run(pulling_query)
    interests_desc = pd.DataFrame([dict(row) for row in result])
print("Shape",interests_desc.shape)
interests_desc.head()

Shape (599, 2)

   ID                                        description
0   0  Web development is the work involved in develo...
1   1  TypeScript is an open-source programming langu...
2   2  A programming language is a formal language co...
3   3
4   4  The career is an individual's metaphorical "jo...

In [9]:
descriptions_db = pd.concat([blogs_desc,interests_desc])
descriptions_db['description'].str.encode('utf-8')
print(descriptions_db.shape)
descriptions_db.head()

(879, 2)

    ID                                        description
0  360  And not just in school, but at home Continue r...
1  380  I have always wondered if a Design system shou...
2  381  Learn the basic concepts behind the most commo...
3  382  Maybe they should all meet the same fate Conti...
4  383  “The current protests are not simply about rac...

0      And not just in school, but at home Continue r...
1      I have always wondered if a Design system shou...
2      Learn the basic concepts behind the most commo...
3      Maybe they should all meet the same fate Conti...
4      “The current protests are not simply about rac...
                             ...
594    In computing, a data warehouse (DW or DWH), al...
595    Google Sheets is a spreadsheet program include...
596    Google APIs is a set of application programmin...
597    Software as a service (SaaS ) (also known as s...
598
Name: description, Length: 879, dtype: object

In [10]:
corpus_text = ""
for index,r in descriptions_db.iterrows():
    corpus_text += r['description']
with open('corpus.txt','w') as t:
    t.write(corpus_text)
    t.close()

In [65]:
processed_corpus = corpus_text.translate ({ord(c): " " for c in "''!@#$%^&*()[]{};:,./<>?\|`~-=_+"})
list_corpus = corpus_text.split(' ')
print(list_corpus)

', 'organizations', 'to', 'gain', 'insight', 'into', 'new', 'markets,', 'to', 'assess', 'demand', 'and', 'suitability', 'of', 'products', 'and', 'services', 'for', 'different', '', 'market', 'segments,', 'and', 'to', 'gauge', 'the', 'impact', 'of', 'marketing', 'efforts.BI', 'applications', 'use', 'data', 'gathered', 'from', 'a', 'data', 'warehouse', '(DW)', 'or', 'from', 'a', 'data', 'mart,', 'and', 'the', 'concepts', 'of', 'BI', 'and', 'DW', 'combine', 'as', '"BI/DW"\nor', 'as', '"BIDW".', 'A', 'data', 'warehouse', 'contains', 'a', 'copy', 'of', 'analytical', 'data', 'that', 'facilitate', 'decision', 'support.A', 'robot', 'is', 'a', 'machine—especially', 'one', 'programmable', 'by', 'a', 'computer—', 'capable', 'of', 'carrying', 'out', 'a', 'complex', 'series', 'of', 'actions', 'automatically.', 'Robots', 'can', 'be', 'guided', 'by', 'an', 'external', 'control', 'device', 'or', 'the', 'control', 'may', 'be', 'embedded', 'within.', 'Robots', 'may', 'be', 'constructed', 'on', 'the', 'lines', 'of', 'human', 'form,', 'but', 'most', 'robots', 'are', 'machines', 'designed', 'to', 'perform', 'a', 'task', 'with', 'no', 'regard', 'to', 'their', 'aesthetics.\nRobots', 'can', 'be', 'autonomous', 'or', 'semi-autonomous', 'and', 'range', 'from', 'humanoids', 'such', 'as', "Honda's", 'Advanced', 'Step', 'in', 'Innovative', 'Mobility', '(ASIMO)', 'and', "TOSY's", 'TOSY', 'Ping', 'Pong', 'Playing', 'Robot', '(TOPIO)', 'to', 'industrial', 'robots,', 'medical', 'operating', 'robots,', 'patient', 'assist', 'robots,', 'dog', 'therapy', 'robots,', 'collectively', 'programmed', 'swarm', 'robots,', 'UAV', 'drones', 'such', 'as', 'General', 'Atomics', 'MQ-1', 'Predator,', 'and', 'even', 'microscopic', 'nano', 'robots.', 'By', 'mimicking', 'a', 'lifelike', 'appearance', 'or', 'automating', 'movements,', 'a', 'robot', 'may', 'convey', 'a', 'sense', 'of', 'intelligence', 'or', 'thought', 'of', 'its', 'own.', 'Autonomous', 'things', 'are', 'expected', 'to', 'proliferate', 'in', 'the', 'coming', 'decade,', 'with', 'home', 'robotics', 'and', 'the', 'autonomous', 'car', 'as', 'some', 'of', 'the', 'main', 'drivers.The', 'branch', 'of', 'technology', 'that', 'deals', 'with', 'the', 'design,', 'construction,', 'operation,', 'and', 'application', 'of', 'robots,', 'as', 'well', 'as', 'computer', 'systems', 'for', 'their', 'control,', 'sensory', 'feedback,', 'and', 'information', 'processing', 'is', 'robotics.', 'These', 'technologies', 'deal', 'with', 'automated', 'machines', 'that', 'can', 'take', 'the', 'place', 'of', 'humans', 'in', 'dangerous', 'environments', 'or', 'manufacturing', 'processes,', 'or', 'resemble', 'humans', 'in', 'appearance,', 'behavior,', 'or', 'cognition.', 'Many', 'of', "today's", 'robots', 'are', 'inspired', 'by', 'nature', 'contributing', 'to', 'the', 'field', 'of', 'bio-inspired', 'robotics.', 'These', 'robots', 'have', 'also', 'created', 'a', 'newer', 'branch', 'of', 'robotics:', 'soft', 'robotics.\nFrom', 'the', 'time', 'of', 'ancient', 'civilization', 'there', 'have', 'been', 'many', 'accounts', 'of', 'user-configurable', 'automated', 'devices', 'and', 'even', 'automata', 'resembling', 'animals', 'and', 'humans,', 'designed', 'primarily', 'as', 'entertainment.', 'As', 'mechanical', 'techniques', 'developed', 'through', 'the', 'Industrial', 'age,', 'there', 'appeared', 'more', 'practical', 'applications', 'such', 'as', 'automated', 'machines,', 'remote-control', 'and', 'wireless', 'remote-control.\nThe', 'term', 'comes', 'from', 'a', 'Slavic', 'root,', 'robot-,', 'with', 'meanings', 'associated', 'with', 'labor.', 'The', 'word', "'robot'", 'was', 'first', 'used', 'to', 'denote', 'a', 'fictional', 'humanoid', 'in', 'a', '1920', 'Czech-language', 'play', 'R.U.R.', '(Rossumovi', 'Univerzální', 'Roboti', '-', "Rossum's", 'Universal', 'Robots)', 'by', 'Karel', 'Čapek,', 'though', 'it', 'was', "Karel's", 'brother', 'Josef', 'Čapek', 'who', 'was', 'the', "word's", 'true', 'inventor.\nElectronics', 'evolved', 'into', 'the', 'driving', 'force', 'of', 'development', 'with', 'the', 'advent', 'of', 'the', 'first', 'electronic', 'autonomous', 'robots', 'created', 'by', 'William', 'Grey', 'Walter', 'in', 'Bristol,', 'England', 'in', '1948,', 'as', 'well', 'as', 'Computer', 'Numerical', 'Control', '(CNC)', 'machine', 'tools', 'in', 'the', 'late', '1940s', 'by', 'John', 'T.', 'Parsons', 'and', 'Frank', 'L.', 'Stulen.', 'The', 'first', 'commercial,', 'digital', 'and', 'programmable', 'robot', 'was', 'built', 'by', 'George', 'Devol', 'in', '1954', 'and', 'was', 'named', 'the', 'Unimate.', 'It', 'was', 'sold', 'to', 'General', 'Motors', 'in', '1961', 'where', 'it', 'was', 'used', 'to', 'lift', 'pieces', 'of', 'hot', 'metal', 'from', 'die', 'casting', 'machines', 'at', 'the', 'Inland', 'Fisher', 'Guide', 'Plant', 'in', 'the', 'West', 'Trenton', 'section', 'of', 'Ewing', 'Township,', 'New', 'Jersey.Robots', 'have', 'replaced', 'humans', 'in', 'performing', 'repetitive', 'and', 'dangerous', 'tasks', 'which', 'humans', 'prefer', 'not', 'to', 'do,', 'or', 'are', 'unable', 'to', 'do', 'because', 'of', 'size', 'limitations,', 'or', 'which', 'take', 'place', 'in', 'extreme', 'environments', 'such', 'as', 'outer', 'space', 'or', 'the', 'bottom', 'of', 'the', 'sea.', 'There', 'are', 'concerns', 'about', 'the', 'increasing', 'use', 'of', 'robots', 'and', 'their', 'role', 'in', 'society.', 'Robots', 'are', 'blamed', 'for', 'rising', 'technological', 'unemployment', 'as', 'they', 'replace', 'workers', 'in', 'increasing', 'numbers', 'of', 'functions.', 'The', 'use', 'of', 'robots', 'in', 'military', 'combat', 'raises', 'ethical', 'concerns.', 'The', 'possibilities', 'of', 'robot', 'autonomy', 'and', 'potential', 'repercussions', 'have', 'been', 'addressed', 'in', 'fiction', 'and', 'may', 'be', 'a', 'realistic', 'concern', 'in', 'the', 'future.\n\nBoston', 'Dynamics', 'is', 'an', 'American', 'engineering', 'and', 'robotics', 'design', 'company', 'founded', 'in', '1992', 'as', 'a', 'spin-off', 'from', 'the', 'Massachusetts', 'Institute', 'of', 'Technology.', 'Headquartered', 'in', 'Waltham,', 'Massachusetts,', 'Boston', 'Dynamics', 'is', 'a', 'wholly', 'owned', 'subsidiary', 'of', 'the', 'Japanese', 'conglomerate', 'SoftBank', 'Group.', 'The', 'company', 'is', 'a', 'pioneer', 'in', 'the', 'field', 'of', 'robotics', 'and', 'it', 'is', 'one', 'of', 'the', 'most', 'advanced', 'in', 'its', 'domain.Boston', 'Dynamics', 'is', 'best', 'known', 'for', 'the', 'development', 'of', 'a', 'series', 'of', 'dynamic', 'highly-mobile', 'robots,', 'including', 'BigDog,', 'Spot,', 'Atlas,', 'and', 'Handle.', '', 'These', 'robots', 'are', 'perhaps', 'most', 'familiar', 'to', 'the', 'world', 'through', 'their', 'highly', 'popular', 'videos', '—', 'the', 'Boston', 'Dynamics', 'YouTube', 'channel,', 'for', 'example,', 'as', 'of', 'May', '2020', 'has', '1.72', 'Million', 'subscribers,', 'making', 'it', 'probably', 'the', 'largest', 'YouTube', 'channel', 'focused', 'on', 'robotics.', 'Since', '2019,', 'Spot', 'has', 'been', 'made', 'commercially', 'available,', 'making', 'it', 'the', 'first', 'commercially', 'available', 'robot', 'from', 'Boston', 'Dynamics,', 'with', 'the', 'company', 'stating', 'its', 'intent', 'to', 'commercialize', 'other', 'robots', 'as', 'well,', 'including', 'Handle.\n\nThis', 'is', 'a', 'timeline', 'of', 'Amazon', 'Web', 'Services,', 'which', 'offers', 'a', 'suite', 'of', 'cloud', 'computing', 'services', 'that', 'make', 'up', 'an', 'on-demand', 'computing', 'platform.Cloud', 'computing', 'is', 'the', 'on-demand', 'availability', 'of', 'computer', 'system', 'resources,', 'especially', 'data', 'storage', '(cloud', 'storage)', 'and', 'computing', 'power,', 'without', 'direct', 'active', 'management', 'by', 'the', 'user.', 'The', 'term', 'is', 'generally', 'used', 'to', 'describe', 'data', 'centers', 'available', 'to', 'many', 'users', 'over', 'the', 'Internet.', 'Large', 'clouds,', 'predominant', 'today,', 'often', 'have', 'functions', 'distributed', 'over', 'multiple', 'locations', 'from', 'central', 'servers.', 'If', 'the', 'connection', 'to', 'the', 'user', 'is', 'relatively', 'close,', 'it', 'may', 'be', 'designated', 'an', 'edge', 'server.\nClouds', 'may', 'be', 'limited', 'to', 'a', 'single', 'organization', '(enterprise', 'clouds),', 'or', 'be', 'available', 'to', 'many', 'organizations', '(public', 'cloud).\nCloud', 'computing', 'relies', 'on', 'sharing', 'of', 'resources', 'to', 'achieve', 'coherence', 'and', 'economies', 'of', 'scale.\nAdvocates', 'of', 'public', 'and', 'hybrid', 'clouds', 'note', 'that', 'cloud', 'computing', 'allows', 'companies', 'to', 'avoid', 'or', 'minimize', 'up-front', 'IT', 'infrastructure', 'costs.', 'Proponents', 'also', 'claim', 'that', 'cloud', 'computing', 'allows', 'enterprises', 'to', 'get', 'their', 'applications', 'up', 'and', 'running', 'faster,', 'with', 'improved', 'manageability', 'and', 'less', 'maintenance,', 'and', 'that', 'it', 'enables', 'IT', 'teams', 'to', 'more', 'rapidly', 'adjust', 'resources', 'to', 'meet', 'fluctuating', 'and', 'unpredictable', 'demand,', 'providing', 'the', 'burst', 'computing', 'capability:', 'high', 'computing', 'power', 'at', 'certain', 'periods', 'of', 'peak', 'demand.Cloud', 'providers', 'typically', 'use', 'a', '"pay-as-you-go"', 'model,', 'which', 'can', 'lead', 'to', 'unexpected', 'operating', 'expenses', 'if', 'administrators', 'are', 'not', 'familiarized', 'with', 'cloud-pricing', 'models.The', 'availability', 'of', 'high-capacity', 'networks,', 'low-cost', 'computers', 'and', 'storage', 'devices', 'as', 'well', 'as', 'the', 'widespread', 'adoption', 'of', 'hardware', 'virtualization,', 'service-oriented', 'architecture', 'and', 'autonomic', 'and', 'utility', 'computing', 'has', 'led', 'to', 'growth', 'in', 'cloud', 'computing.', 'By', '2019,', 'Linux', 'was', 'the', 'most', 'widely', 'used', 'operating', 'system,', 'including', 'in', "Microsoft's", 'offerings', 'and', 'is', 'thus', 'described', 'as', 'dominant.', 'The', 'Cloud', 'Service', 'Provider', '(CSP)', 'will', 'screen,', 'keep', 'up', 'and', 'gather', 'data', 'about', 'the', 'firewalls,', 'intrusion', 'identification', 'or/and', 'counteractive', 'action', 'frameworks', 'and', 'information', 'stream', 'inside', 'the', 'network.A', 'data', 'model', '(or', 'datamodel)', 'is', 'an', 'abstract', 'model', 'that', 'organizes', 'elements', 'of', 'data', 'and', 'standardizes', 'how', 'they', 'relate', 'to', 'one', 'another', 'and', 'to', 'the', 'properties', 'of', 'real-world', 'entities.', 'For', 'instance,', 'a', 'data', 'model', 'may', 'specify', 'that', 'the', 'data', 'element', 'representing', 'a', 'car', 'be', 'composed', 'of', 'a', 'number', 'of', 'other', 'elements', 'which,', 'in', 'turn,', 'represent', 'the', 'color', 'and', 'size', 'of', 'the', 'car', 'and', 'define', 'its', 'owner.\nThe', 'term', 'data', 'model', 'can', 'refer', 'to', 'two', 'distinct', 'but', 'closely', 'related', 'concepts.', 'Sometimes', 'it', 'refers', 'to', 'an', 'abstract', 'formalization', 'of', 'the', 'objects', 'and', 'relationships', 'found', 'in', 'a', 'particular', 'application', 'domain:', 'for', 'example', 'the', 'customers,', 'products,', 'and', 'orders', 'found', 'in', 'a', 'manufacturing', 'organization.', 'At', 'other', 'times', 'it', 'refers', 'to', 'the', 'set', 'of', 'concepts', 'used', 'in', 'defining', 'such', 'formalizations:', 'for', 'example', 'concepts', 'such', 'as', 'entities,', 'attributes,', 'relations,', 'or', 'tables.', 'So', 'the', '"data', 'model"', 'of', 'a', 'banking', 'application', 'may', 'be', 'defined', 'using', 'the', 'entity-relationship', '"data', 'model".', 'This', 'article', 'uses', 'the', 'term', 'in', 'both', 'senses.\n\nA', 'data', 'model', 'explicitly', 'determines', 'the', 'structure', 'of', 'data.', 'Data', 'models', 'are', 'typically', 'specified', 'by', 'a', 'data', 'specialist,', 'data', 'librarian,', 'or', 'a', 'digital', 'humanities', 'scholar', 'in', 'a', 'data', 'modeling', 'notation.', 'These', 'notations', 'are', 'often', 'represented', 'in', 'graphical', 'form.A', 'data', 'model', 'can', 'sometimes', 'be', 'referred', 'to', 'as', 'a', 'data', 'structure,', 'especially', 'in', 'the', 'context', 'of', 'programming', 'languages.', 'Data', 'models', 'are', 'often', 'complemented', 'by', 'function', 'models,', 'especially', 'in', 'the', 'context', 'of', 'enterprise', 'models.Analytics', 'is', 'the', 'systemic', 'computational', 'analysis', 'of', 'data', 'or', 'statistics.', 'It', 'is', 'used', 'for', 'the', 'discovery,', 'interpretation,', 'and', 'communication', 'of', 'meaningful', 'patterns', 'in', 'data.', 'It', 'also', 'entails', 'applying', 'data', 'patterns', 'towards', 'effective', 'decision', 'making.', 'It', 'can', 'be', 'valuable', 'in', 'areas', 'rich', 'with', 'recorded', 'information;', 'analytics', 'relies', 'on', 'the', 'simultaneous', 'application', 'of', 'statistics,', 'computer', 'programming', 'and', 'operations', 'research', 'to', 'quantify', 'performance.\nOrganizations', 'may', 'apply', 'analytics', 'to', 'business', 'data', 'to', 'describe,', 'predict,', 'and', 'improve', 'business', 'performance.', 'Specifically,', 'areas', 'within', 'analytics', 'include', 'predictive', 'analytics,', 'prescriptive', 'analytics,', 'enterprise', 'decision', 'management,', 'descriptive', 'analytics,', 'cognitive', 'analytics,', 'Big', 'Data', 'Analytics,', 'retail', 'analytics,', 'supply', 'chain', 'analytics,', 'store', 'assortment', 'and', 'stock-keeping', 'unit', 'optimization,', 'marketing', 'optimization', 'and', 'marketing', 'mix', 'modeling,', 'web', 'analytics,', 'call', 'analytics,', 'speech', 'analytics,', 'sales', 'force', 'sizing', 'and', 'optimization,', 'price', 'and', 'promotion', 'modeling,', 'predictive', 'science,', 'graph', 'analytics,', 'credit', 'risk', 'analysis,', 'and', 'fraud', 'analytics.', 'Since', 'analytics', 'can', 'require', 'extensive', 'computation', '(see', 'big', 'data),', 'the', 'algorithms', 'and', 'software', 'used', 'for', 'analytics', 'harness', 'the', 'most', 'current', 'methods', 'in', 'computer', 'science,', 'statistics,', 'and', 'mathematics.In', 'computing,', 'a', 'data', 'warehouse', '(DW', 'or', 'DWH),', 'also', 'known', 'as', 'an', 'enterprise', 'data', 'warehouse', '(EDW),', 'is', 'a', 'system', 'used', 'for', 'reporting', 'and', 'data', 'analysis,', 'and', 'is', 'considered', 'a', 'core', 'component', 'of', 'business', 'intelligence.', 'DWs', 'are', 'central', 'repositories', 'of', 'integrated', 'data', 'from', 'one', 'or', 'more', 'disparate', 'sources.', 'They', 'store', 'current', 'and', 'historical', 'data', 'in', 'one', 'single', 'place', 'that', 'are', 'used', 'for', 'creating', 'analytical', 'reports', 'for', 'workers', 'throughout', 'the', 'enterprise.The', 'data', 'stored', 'in', 'the', 'warehouse', 'is', 'uploaded', 'from', 'the', 'operational', 'systems', '(such', 'as', 'marketing', 'or', 'sales).', 'The', 'data', 'may', 'pass', 'through', 'an', 'operational', 'data', 'store', 'and', 'may', 'require', 'data', 'cleansing', 'for', 'additional', 'operations', 'to', 'ensure', 'data', 'quality', 'before', 'it', 'is', 'used', 'in', 'the', 'DW', 'for', 'reporting.\nExtract,', 'transform,', 'load', '(ETL)', 'and', 'extract,', 'load,', 'transform', '(E-LT)', 'are', 'the', 'two', 'main', 'approaches', 'used', 'to', 'build', 'a', 'data', 'warehouse', 'system.Google', 'Sheets', 'is', 'a', 'spreadsheet', 'program', 'included', 'as', 'part', 'of', 'a', 'free,', 'web-based', 'software', 'office', 'suite', 'offered', 'by', 'Google', 'within', 'its', 'Google', 'Drive', 'service.', 'The', 'service', 'also', 'includes', 'Google', 'Docs', 'and', 'Google', 'Slides,', 'a', 'word', 'processor', 'and', 'presentation', 'program', 'respectively.', 'Google', 'Sheets', 'is', 'available', 'as', 'a', 'web', 'application,', 'mobile', 'app', 'for', 'Android,', 'iOS,', 'Windows,', 'BlackBerry,', 'and', 'as', 'a', 'desktop', 'application', 'on', "Google's", 'ChromeOS.', 'The', 'app', 'is', 'compatible', 'with', 'Microsoft', 'Excel', 'file', 'formats.\nThe', 'app', 'allows', 'users', 'to', 'create', 'and', 'edit', 'files', 'online', 'while', 'collaborating', 'with', 'other', 'users', 'in', 'real-time.', 'Edits', 'are', 'tracked', 'by', 'user', 'with', 'a', 'revision', 'history', 'presenting', 'changes.', 'An', "editor's", 'position', 'is', 'highlighted', 'with', 'an', 'editor-specific', 'color', 'and', 'cursor', 'and', 'a', 'permissions', 'system', 'regulates', 'what', 'users', 'can', 'do.', 'Updates', 'have', 'introduced', 'features', 'using', 'machine', 'learning,', 'including', '"Explore",', 'offering', 'answers', 'based', 'on', 'natural', 'language', 'questions', 'in', 'a', 'spreadsheet.Google', 'APIs', 'is', 'a', 'set', 'of', 'application', 'programming', 'interfaces', '(APIs)', 'developed', 'by', 'Google', 'which', 'allow', 'communication', 'with', 'Google', 'Services', 'and', 'their', 'integration', 'to', 'other', 'services.', 'Examples', 'of', 'these', 'include', 'Search,', 'Gmail,', 'Translate', 'or', 'Google', 'Maps.', 'Third-party', 'apps', 'can', 'use', 'these', 'APIs', 'to', 'take', 'advantage', 'of', 'or', 'extend', 'the', 'functionality', 'of', 'the', 'existing', 'services.\nThe', 'APIs', 'provide', 'functionality', 'like', 'analytics,', 'machine', 'learning', 'as', 'a', 'service', '(the', 'Prediction', 'API)', 'or', 'access', 'to', 'user', 'data', '(when', 'permission', 'to', 'read', 'the', 'data', 'is', 'given).', 'Another', 'important', 'example', 'is', 'an', 'embedded', 'Google', 'map', 'on', 'a', 'website,', 'which', 'can', 'be', 'achieved', 'using', 'the', 'Static', 'maps', 'API,', 'Places', 'API', 'or', 'Google', 'Earth', 'API.Software', 'as', 'a', 'service', '(SaaS', ')', '(also', 'known', 'as', 'subscribeware', 'or', 'rentware)', 'is', 'a', 'software', 'licensing', 'and', 'delivery', 'model', 'in', 'which', 'software', 'is', 'licensed', 'on', 'a', 'subscription', 'basis', 'and', 'is', 'centrally', 'hosted.', 'It', 'is', 'sometimes', 'referred', 'to', 'as', '"on-demand', 'software",', 'and', 'was', 'formerly', 'referred', 'to', 'as', '"software', 'plus', 'services"', 'by', 'Microsoft.SaaS', 'applications', 'are', 'also', 'known', 'as', 'Web-based', 'software,', 'on-demand', 'software', 'and', 'hosted', 'software.', 'The', 'term', '"software', 'as', 'a', 'service"', '(SaaS)', 'is', 'considered', 'to', 'be', 'part', 'of', 'the', 'nomenclature', 'of', 'cloud', 'computing,', 'along', 'with', 'infrastructure', 'as', 'a', 'service', '(IaaS),', 'platform', 'as', 'a', 'service', '(PaaS),', 'desktop', 'as', 'a', 'service', '(DaaS),', 'managed', 'software', 'as', 'a', 'service', '(MSaaS),', 'mobile', 'backend', 'as', 'a', 'service', '(MBaaS),', 'datacenter', 'as', 'a', 'service', '(DCaaS),', 'and', 'information', 'technology', 'management', 'as', 'a', 'service', '(ITMaaS).\nSaaS', 'apps', 'are', 'typically', 'accessed', 'by', 'users', 'using', 'a', 'thin', 'client,', 'e.g.', 'via', 'a', 'web', 'browser.', '', 'SaaS', 'has', 'become', 'a', 'common', 'delivery', 'model', 'for', 'many', 'business', 'applications,', 'including', 'office', 'software,', 'messaging', 'software,', 'payroll', 'processing', 'software,', 'DBMS', 'software,', 'management', 'software,', 'CAD', 'software,', 'development', 'software,', 'gamification,', 'virtualization,', 'accounting,', 'collaboration,', 'customer', 'relationship', 'management', '(CRM),', 'management', 'information', 'systems', '(MIS),', 'enterprise', 'resource', 'planning', '(ERP),', 'invoicing,', 'human', 'resource', 'management', '(HRM),', 'talent', 'acquisition,', 'learning', 'management', 'systems,', 'content', 'management', '(CM),', 'geographic', 'information', 'systems', '(GIS),', 'and', 'service', 'desk', 'management.', 'SaaS', 'has', 'been', 'incorporated', 'into', 'the', 'strategy', 'of', 'nearly', 'all', 'leading', 'enterprise', 'software', 'companies.According', 'to', 'a', 'Gartner', 'estimate,', 'SaaS', 'sales', 'in', '2018', 'were', 'expected', 'to', 'grow', '23%', 'to', '$72', 'billion.']

In [66]:
vocab = list(set(list_corpus)) # This works well for a very small corpus
print(vocab)

, 'terraforming.', 'representations', 'brand', 'subtitled:', 'acute', 'scientists,', 'version.\nMigrations', '(ápous),', 'Multilayer', 'capital', 'Virtual', 'sections,', 'Periodic', 'guns/cannons', 'concerned.', 'discussion', 'facilitate', 'explains', 'Techniques', 'loops.', 'involved', 'neck', 'weapon', 'class', 'Bishay,', 'Conferences.', 'so.', 'conceptualize', 'Championships:', 'sheet', 'St', '7230', 'variable', 'unlikely', 'Waterloo', 'first,', 'genetic', '.', '()', 'bibliophile', 'dependent".\nSpeech', 'training.The', 'Fifth', 'Fair', 'philosophy",', 'gates.\nThere', 'Dynamics’', 'settings', 'header,', 'Terence', 'come', 'Anglo-Saxon', 'regulators', 'Howard', 'Hippo', 'existential', 'agriculture,', 'held', 'standpoint.', 'subscribing', 'racial', 'result,', 'Second', 'parallelism.', 'thousand', 'Eurasia', 'standards.', 'abilities', 'Student', 'Pose', 'patterns', 'vendors', 'conceptual', 'suggesting', '(mutating),', 'message.The', 'consistent', 'trigger', 'attacks', 'ever', 'Digital', 'modes', 'I’v...Practical', 'calls', 'scanned', 'Max', 'P...To', 'cloud-computing', 'near-sightedness,', '3.0,', 'aquifers.', 'conclusion,', 'Since', 'dog', 'Renaissance,', 'Cowboy', 'alike', 'Toxic', 'Verwandlung")', 'Education,', '...White-Box', 'Marketplace', 'gravity,', 'code,', 'culture.\nMalta', 'emergent', 'constraints.', 'Jim', '1995),', 'Force', 'critically', 'classifiers', 'observation.', 'types.\nAccording', "Turing's", 'causes', 'compiles', "state's", 'follows', '{1}{2}}\\left({\\frac', 'instruments.', '1822', 'Engine,', 'platform-providing', 'constructs', 'arises', 'aesthetic', 'frailty,', '2019.Heroku', 'sources.', 'world.Cascading', 'wxPython,', 'unlimited', 'Mentorship', 'analyzes', 'reported.', 'MPEG-H', 'fifty', 'I’ve', 'centre', 'nationally', '(EU),', '(IaaS),', 'actions', 'tacit', 'Store', 'Tolpuddle', 'prohibition.The', 'careers.In', 'worm,', 'like-minded', '(EC2),', 'AI)', 'applied,', '(particularly,', '1994', 'CSS', 'behavioral', 'Bayes,', 'reform."Law', 'anger', 'flyway', 'Armstrong', 'Sex', 'space)', 'possibly', 'authentication,', '(USA),', 'directed', '1838', 'production-...Whereas', 'specifics', 'well-functioning', '"flexibility', 'proprietor', 'sensationalist,', 'statesmen', 'spheres', 'official".', 'Qt', '(any', 'Dylan,', 'restrict', 'pedagogy', 'sulfuric', 'privacy', 'second-order', 'Jesse', '2.51', 'entirely', 'Registered', 'unrelated', 'code:', 'forcing', 'coated', 'Other', 'Google.', 'bit-level', 'got', 'animals,', 'Lives', '(IR).', 'Apple’s', 'answered.', 'son', 'hard', 'Declaration', 'xenophobic', 'printers,', "continent's", 'composed', 'version,', 'Outside', 'Bavaria.\nIn', 'Nirvana,', 'chat', 'workers', '"call', '1686])', 'popularized', '(kybernētikḗ),', '1506', 'Planet', 'Wreden', 'aesthetics,', 'Loneliness', 'D3.js', '405,000', 'Requests', 'verify', 'valuation', 'payment.', 'flag', 'FIS', 'possession,', 'polyphenism', 'sex,', 'treaty.Consciousness', 'dimensions.Time', 'not-very-simple', 'unconsolidated', '1999,', 'rail.', 'post-analysis.', ',', 'not).A', 'farming,', 'posed', 'heat,', 'Lata', 'dot', 'abide', 'computing:', 'circuitry', '(ISPs)', 'signup,', 'R.U.R.', 'shoes.', 'System.', 'cyber', 'GDP.', 'programming"', '1920s.', 'large,', 'systems.\nSub-domains', 'sufficient', '20–100', 'quantum-mechanical', 'ever-increasing', 'smell,', 'comic', 'License.\n\nDorset', 'ideals.', 'academic', 'Insider.', 'Cornish', "AWS'", 'feminism', 'showdown', '(lack', "Dijkstra's", 'loneliness', '19th', 'costly', 'strings', 'Britons', 'indexed', 'word', '(commonly', '$3,000', 'Rebecca', 'Git,', 'populous,', 'UWP', '"discrimination', 'girls.', 'letters,', 'audiences', '(PODC)', 'pseudo-scientific,', 'figure', 'Pact', 'jazz', 'Bezos', 'genocides', 'infections', 'Peace', 'harassment,', 'reflective', 'Microsystems', 'client-side', 'shows,', 'Authentication', 'libertarian', 'therapies', 'pricing,', 'Domain', 'village', 'characteristics', 'Place', 'estimate,', 'Neumann.', '4,', 'varyingly', 'platform,', 'referenced', 'connects', 'rearing', 'City.\nPaleo-Indians', 'gifted', '1930s,', 'Foster', "d'état.", 'network.A', 'identical', 'needing', '17', 'me', 'Services.', 'gauge', 'language.', 'Investigation', 'extractive', 'usage;', 'surpass', 'editor-specific', 'carbohydrates', 'Aragonese', 'June', 'registered,', 'Christians,', 'geopolitical', 'control', 'processing.', 'Laplace', 'relied', '1955.', 'synonym', 'brief', 'latency-sensitive', 'tech', 'includes,', 'films', 'pictograms.', 'Efforts', 'virtually', 'polyphenism,', '(Google', 'gesture', 'Which', 'transportation.', 'Freed.', 'signals.', 'econometrics', 'texts,', 'NetMarketShare', 'husband,', 'organizations.', 'trainability', '8.08', 'California,', 'royalty,', 'designers.', 'goals.', 'displaced', 'view,', 'fabricated', 'anthologies.', 'music,', 'variables,', 'situations', 'infrastructure.', 'traversal', 'nurses,', 'Wooden', 'Analytics,', 'overturned', 'designer.Software', 'query,', 'criminal', 'aether', '"preeminent', 'watershed', 'ship', 'YouTube.', 'money,', 'occasionally', 'nationwide', 'self-efficacy,', 'Kong,', 'both,', 'curriculum', 'professionals,', 'fifth-largest', '(TP)', 'synapses.', 'language.SQL', 'diagrams,', 'leather', 'http://www.example.com/articles/21', 'functioning.', 'Vladimir', 'accounting', 'statistics,', 'License', 'desirable,', 'in', 'SOAP).', 'demand.Cloud', '"products."', 'November', '"film"', 'harpoon', 'respectively,', '(cytosine', 'like', 'Italians,', 'innovations.', '4th-generation', 'profile', 'traditional', 'upload', 'M...An', 'study.', '"heads"', 'Cup', 'betting.\nIn', 'practiced', 'states.Natural', 'divine', 'Sheets,', 'dice', 'owners.', 'using', 'mission,', 'business.\nThe', 'Scholarship', "education's", '2.8', 'biased', 'conflicts,', 'reported,', 'isolation.', 'C++14', 'Stanford', 'steepest', 'overlapping', 'Cascade', 'request-based', 'environment),', 'suggestion', 'Tezos', 'decriminalized', '(discussed', 'Apodiformes', 'aircraft', 'orders.', 'Ng', 'guanine', 'chronology', 'omits', 'university,', 'prenatally,', 'offerings', 'essays.', 'Vernor', 'state.\nMost', 'Myron', 'internet', 'fields),', 'Founded', 'According', 'robo-car,', 'junk', 'Singularity,', 'BSD-style', '60.9', 'almost', 'followed.', 'observed', 'websites', 'Qubits', 'workplace,', 'establish,', 'closest', 'uncertainty', 'Robots', 'carrion.', 'derives', 'environment', 'shrimp)', '1981', 'ability)', 'OS-level', '1833:HK,', 'Ashkenazi', '"methods"', 'lifelike', 'Authorities', '(ETL)', 'recipient', 'repositories.\nAs', 'scope.\nInterrupts', 'Instead', 'i.e.', 'T...Single-Label', 'Android', 'bet', 'management,', 'hundred', '(up', 'execution', 'augmented', 'consumers', '(XD)', 'politics.', 'some,', 'hands', 'Sichuan,', 'Celtic', 'Paul', 'Testament', 'Different', 'cross-platform,', '(1898–1980),', 'Runtime', 'normally.', 'Kingdom.', 'II,', '(100%', 'inequalities', 'opposed', 'orientations', 'candidates', 'incorporating', 'theory:', 'purines.', 'discrimination', 'evaluate', 'rule.\nA', 'risky', 'RAM,', "'inquiry;", 'technical', 'electoral', 'Peninsula.', 'reclassified', 'interface.A', 'contract', 'robots,', 'outcomes', '2', 'Hemisphere.', 'limitedly,', 'StoreProc,', '"logit";', 'Aragonese,', 'supercomputer', 'full-time', "Euclid's", 'suffer', 'deferred', 'time"', 'junta', 'many,', 'inference,', 'aristocracy,', 'Netflix,', 'apathy,', 'proved', 'NumPy', 'regulation)', 'respectively', 'Limitations', '(seasons', 'storytelling', 'equilibrium', 'high...Companies', '67', 'domination', '("heads"', 'Wild', 'predetermined', 'domains.In', '(TOPIO)', 'remotely', 'Movement,', 'TL.TensorFlow', 'officially', '114,000', 'worldwide', 'mid-19th', 'conversations', 'punishment.The', 'founder', '0.8', 'i.e.,', 'violations', 'symptoms', 'deficient', 'will,', 'computer—an', '24,', 'Apple', 'automaton),', 'Oceania,', 'detailed', 'blueprints,', 'fever,', '[ɡɾaˈna]', 'Chalcedon', 'private', 'problem-solving,', 'complaints,', 'occurred.', 'others,', 'Rights.\nThe', 'signal).', 'George', 'Meridian', 'ties', 'virtues', 'detectives;', '(null', 'psychology.Serverless', 'motion', 'reconciliation', 'Frankenberg', 'naked.\nThe', 'mob', 'spending,', 'illustrated', 're-evaluate', 'Five', 'sporting,', 'City.', 'signals.\nDecoding', 'commerce.', 'replication,', 'indicating', 'school-age', 'CPG', 'Attendees', 'eukaryotic', 'asexual', 'historia,', 'dare', "viewer's", 'means', 'active', 'consciousness.Python', 'polymorphisms', 'remain', '‘markerless’', 'writer\nMartyn', 'genders,', 'express', 'mastery.', 'exchanging', 'Regis;', 'crime.', 'Open', 'mechanical', "It's", 'clarify', 'Extensions', 'C++,', 'Holland', 'declares,', '1918', 'puppets', 'K.', 'accelerating', 'second-degree', 'generation', 'channels', '(gun', 'China,', 'decoding.', 'book,', 'BAFTAs.', 'legal', 'clouds),', 'monitor', 'Tech:NYC,', 'O.\nThe', '(try/catch,', 'prevents', 'policy', 'labeling', 'NATO', 'eye', 'Prediction', 'division,', 'ἱστορία,', 'investigates', 'subject.', 'pilot', 'Whole', 'Wickersham', 'musteloid.', 'to', '"nerve', "Earth's", 'now-discredited', 'trivializing', 'impulse', 'influenced', 'hand,', 'news,', 'heresy.Creativity', 'methodologies,', 'gay', 'with)', 'noble', 'sanction', 'East,', '(Java', 'service)', 'grown', 'killing', 'allows', '1.0', 'against', 'awakening,', 'symbolically', 'Owain', 'Model', 'launch', 'subsidiary.', 'validating', 'country.\nThere', 'morph', 'notably', 'adventures', 'parchment,', 'apply()', 'provisioned', 'within";', 'p', 'unofficial', 'judgment.', '2014,', 'Library\nRobert', "programmer's", 'ported', 'skilled', '(1999–present)', 'sake', 'corrected.', 'raised', 'reduced-complexity', 'volunteer', '(smartphones', 'fountains,', 'revolt', 'Nazareth.', 'performed,', 'tasks.\nMachine', 'Globes', 'Storm.Apache', '"Explore",', 'decorative', 'capitalism', 'innocence.', 'anxiety,', 'helplessness.', '"alt-right"', 'assign', 'Bootcamp', 'fantastic.', '{1}{\\sigma', 'free-swinging', 'server-', 'OpenAI', 'Leading', 'establish', 'rent', 'April', 'user-testing', 'theory),', 'Hypertext', 'made', 'typed,', "learners'", 'longer', 'periodized', '1980s,', 'renew', 'address)', 'decision",', 'substituted', 'N·s', 'reports', 'Trow', 'speed,', 'provocation,', 'Parable.\nThe', 'alias', 'retrieving', 'reforms', 'Neo-Luddism,', 'technology".', 'Township,', 'provided', 'handwriting', 'Text', 'Invention', 'announced', 'century,', 'sample', 'dataset.', '(doing', 'tradeoff.\n\nSupervised', 'Muslim', 'open-ended', 'power.', 'monarchy', 'first-generation', 'readily', 'Korotkevich,', 'Injustice!', 'obstacles', 'eastern', 'elicits', 'taxation,', 'Bell', 'clues', 'race,', 'greater', 'tips', 'Church–Turing', 'respectively.', 'Philosophers', 'Property', 'analog', 'smart', 'box', 'Users,', 'measurements.', 'falsifiable', 'trust', 'Go”,', 'help)', '3000', 'texture', 'model-building', 'well,', 'long-term', 'dashes', 'metal', 'platform.Cloud', 'Image', 'piecework', 'Modern', 'analysis.', 'experts,', 'precondition', 'systems', 'press.Empathy', 'submitted', 'approaching', '...Its', 'Uncertainty', 'understandable', 'Slides,', '(for', 'suggested', 'carrier', 'interpreted', '("logic"', "band's", 'leading', '("mail")', 'Revolutions,', 'took', 'coordinate', '(print', 'cnidarians', 'architecture.', 'fish,', 'lines.Libertarianism', 'judgment,', 'non-parent', 'protein', 'as,', 'executor', 'depersonalization,', 'Fishburne,', 'north-west,', "'wearable", '"pay-as-you-go"', 'Religious', 'responsibility', 'unclear,', 'certification', 'Business-to-business', 'abolition', 'Ski', 'everyone', 'Analytics', 'well-being.', 'Y...How', 'notions', 'colleague', 'telephony,', 'Gradient', '\\limits', 'SP)', 'frame', 'selected.\nPotential', 'receive', 'Discourse', 'Inner', '(meaning,', 'Ίος,', 'foundations', 'u', 'headsets.\nSince', 'free.\nStarting', "EU's", 'environments.', 'worker', 'appointed', 'reform', 'dimorphism,', 'argument', 'equity.\nEducational', 'globalization.', 'Systems.', 'multi-core', 'antipsychotics,', 'online', 'observations', 'city;', 'Intelligence",', 'peripheral', 'pass/fail', '(October', 'funds', 'Amazon),', 'away', '1993', 'writers', 'select', 'wrapped', 'unarticulated', 'reciprocal', 'manages', 'deoxyribose,', 'Autonomous', 'Eng...For', 'Tropical.', 'deterministic;', 'proposed,', 'inhibited,', 'Politics,', 'multicellular', 'electromagnetic', 'mountainous', 'salary,', 'So,', 'decimals,', 'backwards', 'adolesc...We', 'objectives.', 'photographs', 'n-tier', 'formation', 'languages,', 'lens', 'Trenton', '"looking', 'activated', 'licence', 'Daughters.', 'shelter', 'processing;', '"perspective"', 'messaging.', 'corporālis', 'τέσσερεις', 'three-dimensional', 'lot.Electoral', 'entanglement', '(introduced', 'performance.\nA', 'employers', 'unfairly', 'Work),', 'heterogeneous', 'Excel', 'withdrawal', '172', 'publisher,', 'swipe,', '"study,', 'behaviors', 'broadcast).Widely', 'organized', '(EDW),', 'prescriptions', 'X', 'stricter', 'tool.', 'series.\nTime', 'considerations,', 'substantive', 'scientific', 'Preprocessor.PHP', 'stockholder', 'Narcotic', 'light.', 'Informally', 'axons,', 'classic', 'publishes', 'SGML\u202f.', 'left-wing', 'how', 'Roediger', 'R,', 'treated,', 'gender,', 'domain.Boston', '(meaning).', 'morph.\nThe', 'slowly', 'observable', 'strap', 'needed:', 'alter', 'providing', 'raster', 'Cavendish', 'format', 'ownership.', 'homelessness,', 'total,', 'BC', 'Teachers', '(conversion', 'society', 'flaws', 'tables,', 'overlap.', 'modalities,', 'colorimetry,', 'normalizes', 'total', 'companies.\nAmazon', '7,', 'positive', 'Waterston', 'Xojo.Numba', 'apprentice', 'sent', 'behavior).', 'Systems', 'figuratively', 'right-hand', 'Chrome', 'abstinence-only-until-marriage', 'component', '북조선,', 'home,', 'Schema', 'Standardization', 'Christian.', 'pressure,', 'fostering', 'analogous', 'LP', 'objectives,', 'restaurant', 'it....There', 'neuron', 'gave', 'countries.Sentiment', 'ribonucleic', 'projects.', 'Lindsay', 'conclusions', 'Matplotlib.\nMatplotlib', '1947,', 'Search).', 'Morley', 'AKS', 'Welsh-speakers', "player's", 'node.\nThe', 'inform', 'damp', 'drilling,', 'irreconcilable', 'generated', 'ordering,', 'Numeric,', 'teach,', 'continue', 'Collection', 'dimensions', 'Foundation', 'predictable.\nThe', 'department', '"entrepreneurship"', '1852,', 'aspirations.', 'sexual', 'fusion', 'Inc.Data', 'Computers', 'Steno,', '“Write...Math', 'do.', 'gend...Since', '"Neo",', 'processes,', 'systems)\nA', 'permission.', 'priced', 'documented', 'multisport', "Rails'", 'any', 'unit.The', 'learning.\nIn', 'square.', 'properties.Psychoactive', 'errno,', 'seated', 'show', 'carrying', 'Within', 'powers.', 'resurgence', 'Class', 'Predator,', 'seminary', 'united', 'manipulated', '#include', 'avid', 'owned', 'middle-class,', 'absence,', 'completion,', 'mythical.', 'haunted', '\nPing', 'multi-level', 'covered', 'varies', 'note:', 'brick-and-mortar', 'soul', 'anti-paternalist,', 'storage', 'structures.', 'confusion', 'Either', 'DeKalb', 'verbal', 'multi-platinum', 'companies.According', 'whole;', 'free-standing', 'styles,', 'everywhere', 'rhetoric,"', 'redundancy.In', 'human-readable', '3.', 'kenshō,', 'challenged', 'singular', '600,000', '"fake', 'phenomenon,', 'worn', 'science.A', 'inventor.\nElectronics', 'unity', 'poetry', '"The', 'Autumn', '(Uber', 'high-volume', 'locally', 'matters,', 'magic,', 'computer.ALGO', 'family,', 'devices),', '(e-commerce', 'lose', 'nieces,', '(Dev)', 'removals,', 'structures', '1.1', 'reform.', 'boolean', 'Library)', 'Army', 'Knt', 's\n', 'result.Information', '500,000', 'NumPy.', 'abstract,', 'Ventures', 'Chile', 'blockchains', 'leadership.', 'closed-loop', '7,500', 'time-sharing', '(SaaS)', 'guidance', 'idealized', 'microcontrollers', 'citizenship', 'Hutcheson', 'guide,', 'Brown—resulting', 'engaged', 'males.', 'institution,', 'Alexa,', 'Census', 'VuMark.', 'percolating', '2016.In', 'v.', 'Chas', 'Federativa', 'arrays', 'recommended', 'mediate', 'word.', 'vegetation,', 'components.Ios,', 'situations).', '1997.', 'County.', '13th', 'Names', 'Calculation).', 'widest', 'analyst', 'distinct:', 'location)', 'birthplace', 'controllability', 'century.Neuro-linguistic', 'walk,', 'exhibits', 'scroll.', '1780s.', 'animation.', 'paper)', '(AI),', '),', 'railroad.', 'readings', 'anger,', '2009', 'utilitarian', 'suits', 'SR-IOV', 'formally', 'Abbey,', 'Bonacci', 'shoe).', '2012)', 'Intel).', 'mimicry),', 'representation', 'Americas;', 'military,', 'time', 'substance', 'forth', '\nConsequently,', 'BEL-ing-ham)', 'sensory,', 'raid', 'memorized,', '"whiteness"', 'unfavorably', 'scalable', 'burned', '(common)', 'proclamations,', 'plans,', 'British.', 'ghosts', 'pattern.', 'alphabets', 'experiments', 'devices—that', '"Emotional', 'statue.Statues', 'Commercial', 'figure).', 'convex', 'Court', 'Most', 'broader', 'measure', 'number,', 'stood', 'DBSCAN,', 'for-profit', 'FPN,', 'video,', 'revolution,', 'knowledge)', 'process.The', 'charismatic', 'caissoning', 'programs', 'especially', 'acceptance"', 'resolve', 'constant', 'series.', 'anonymized,', 'connections.In', 'unalterable,', 'Netcat\u200a—\u200aTCP/IP', 'faster', 'Raw', 'anatomically', 'beings",', 'rubies,', 'embarrassment,', 'Machine', 'values', 'continued', 'whether', 'WebSockets', '(syntax-directed', 'anarchist', 'small,', 'department,', '(SARS‑CoV‑2).', 'really', 'politically', 'URLs.', 'family.', 'backbone.', 'synonymously', 'silver', 'NumPy)', 'mesh', 'Emancipation', 'came', 'auto', 'topics.', 'whereupon', 'stays', 'demographics,', 'items.', 'portrays', 'expression', 'extension"', 'Middle-East,', 'interviewer', 'non-degree', 'response', 'desk', 'Keaton', 'man', 'Ethereum', 'Schools', 'consciousness', 'explored', '"Seattle"', 'Joel', 'Asia,', 'enclosure', 'design)', 'reformulated', 'dissonance', '1,', 'reflection,', 'tubulin\n(P)rednisone', '11th-century', 'storing', 'luggage,', 'societies.\nA', 'negative").', 'telephone', 'subroutine,', 'particles', 'deals', 'However,', 'One,', 'records', 'colors', 'approach,', 'ending', 'others),', 'crossword', 'third-largest', 'commercialized', 'Canada–United', 'marketing).Regardless', 'attends', 'iconoclasm', '»...A', 'mentorship', 'verified.', 'stretching', 'synthesizes', 'treated', 'craft', 'middle-class', 'Opponents,', 'military', 'around', 'rooms,', 'self-service', 'optimized', 'future.\nSnapchat', 'Minjujuŭi', '(DVB-S', 'Spark', 'reversible', 'notation,', 'exists.The', 'Time),', 'polarized', 'Productivity', 'chances', 'derived', 'trend', 'foreign', 'lieu', 'communicare,', 'may', 'reign', 'complemented', 'majority', 'interfaces.A', 'tangible', 'departmental,', 'Interface', 'conformity', 'nursed', 'emancipation', 'law,', 'behavior,', 'extensive', 'connections.', 'types.\nMany', 'labeling;', 'empt...If', 'computationally', 'Council.\nA', 'Benefits', 'U.S.–Canada', 'developers,', 'Neither', '(LSTMs)', 'priori', 'open-data', '...By', 'monitoring,', 'Southeast,', '(decision', 'advertisement', 'Streaming', 'trading', 'toolchain', 'neurology,', 'informally', 'painting,', '(corresponding', 'applying', 'treaty', 'write,', 'store', 'diverge', 'γ\n', 'inferred', 'version', 'peer-to-peer', 'recursive', 'continent', 'internationally.LGBT,', 'charged', 'increases.', 'drivers.”', 'reproducing', '»...Advancements', 'Amarillo,', 'athletic', '"geometrical', 'are.', 'Jakob', 'it).\nThe', 'correspond', 'continue".', 'dimensions.', 'gradually', 'zooids,', 'TL', 'indicates', 'Transition', 'problems,', 'discouraged.', 'productivity', 'tracking,', 'wind', 'readin...Because', 'Fibonacci,', 'Plaid', 'reflection', 'hospital', 'nineteenth', 'abortion),', 'panned', 'time.In', 'behave', '2018,', 'separator,', 'easier,', 'multi-line', 'present.Stories', 'diverse,', 'Arab', 'embraces', 'Nervous', 'Creator,', 'textile', 'founder.', 'tired,', 'one', 'heir', '(31%;', '»...Vacuum', 'summer', 'Turbo', 'gradient)', 'making', 'pleasurable', 'mimics', '(tyranny).\nWhile', 'illustration', 'expire', 'expectations', '70', 'Freeman,', 'Azure,', 'finish', '(polysaccharides),', 'mph).', 'Napoleonic', 'chiropractors', 'Furthermore,', 'philosophies', 'learners', 'factor.PHP', 're-identification,', '50,000', 'occurring']

In [78]:
word_counter = collections.Counter()
for term in list_corpus:
 
    if len(term) > 3:       word_counter.update({term: 1})
vocab = word_counter.most_common(200) # 200 Most common terms
print('Vocab Size: {}'.format(len(vocab))) 
print(word_counter.most_common(100))

Vocab Size: 200
[('that', 894), ('with', 661), ('from', 477), ('which', 390), ('such', 358), ('data', 345), ('also', 311), ('other', 305), ('have', 295), ('used', 279), ('more', 198), ('most', 188), ('been', 185), ('their', 177), ('social', 177), ('design', 168), ('many', 159), ('often', 155), ('including', 155), ('software', 153), ('between', 149), ('some', 147), ('computer', 146), ('Continue', 141), ('through', 138), ('into', 137), ('include', 136), ('reading', 135), ('system', 135), ('than', 132), ('using', 131), ('human', 131), ('different', 130), ('they', 127), ('United', 118), ('This', 116), ('learning', 115), ('language', 115), ('development', 114), ('this', 113), ('called', 113), ('programming', 111), ('term', 108), ('known', 108), ('time', 103), ('form', 103), ('first', 101), ('were', 99), ('systems', 98), ('over', 98), ('process', 98), ('these', 97), ('being', 95), ('information', 95), ('about', 93), ('research', 90), ('part', 89), ('within', 88), ('developed', 88), ('based', 87), ('people', 83), ('well', 82), ('where', 79), ('only', 78), ('when', 78), ('while', 78), ('mobile', 77), ('both', 77), ('physical', 76), ('applications', 75), ('study', 75), ('machine', 74), ('will', 72), ('computing', 72), ('typically', 72), ('same', 69), ('each', 69), ('States', 69), ('science', 68), ('common', 67), ('application', 67), ('various', 67), ('considered', 67), ('user', 66), ('usually', 66), ('control', 66), ('series', 64), ('business', 64), ('specific', 64), ('code', 63), ('methods', 63), ('education', 63), ('public', 62), ('health', 62), ('Google', 61), ('natural', 61), ('under', 60), ('number', 60), ('white', 59), ('world', 59)]

In [79]:
vocab.append(('UNKNOWN', 1))
Idx = range(1, len(vocab)+1)
vocab = [t[0] for t in vocab]

Word2Idx = dict(zip(vocab, Idx))
Idx2Word = dict(zip(Idx, vocab))

Word2Idx['PAD'] = 0
Idx2Word[0] = 'PAD'
VOCAB_SIZE = len(Word2Idx)
print('Word2Idx Size: {}'.format(len(Word2Idx)))
print('Idx2Word Size: {}'.format(len(Idx2Word)))
print(Word2Idx)

Word2Idx Size: 202
Idx2Word Size: 202
{'that': 1, 'with': 2, 'from': 3, 'which': 4, 'such': 5, 'data': 6, 'also': 7, 'other': 8, 'have': 9, 'used': 10, 'more': 11, 'most': 12, 'been': 13, 'their': 14, 'social': 15, 'design': 16, 'many': 17, 'often': 18, 'including': 19, 'software': 20, 'between': 21, 'some': 22, 'computer': 23, 'Continue': 24, 'through': 25, 'into': 26, 'include': 27, 'reading': 28, 'system': 29, 'than': 30, 'using': 31, 'human': 32, 'different': 33, 'they': 34, 'United': 35, 'This': 36, 'learning': 37, 'language': 38, 'development': 39, 'this': 40, 'called': 41, 'programming': 42, 'term': 43, 'known': 44, 'time': 45, 'form': 46, 'first': 47, 'were': 48, 'systems': 49, 'over': 50, 'process': 51, 'these': 52, 'being': 53, 'information': 54, 'about': 55, 'research': 56, 'part': 57, 'within': 58, 'developed': 59, 'based': 60, 'people': 61, 'well': 62, 'where': 63, 'only': 64, 'when': 65, 'while': 66, 'mobile': 67, 'both': 68, 'physical': 69, 'applications': 70, 'study': 71, 'machine': 72, 'will': 73, 'computing': 74, 'typically': 75, 'same': 76, 'each': 77, 'States': 78, 'science': 79, 'common': 80, 'application': 81, 'various': 82, 'considered': 83, 'user': 84, 'usually': 85, 'control': 86, 'series': 87, 'business': 88, 'specific': 89, 'code': 90, 'methods': 91, 'education': 92, 'public': 93, 'health': 94, 'Google': 95, 'natural': 96, 'under': 97, 'number': 98, 'white': 99, 'world': 100, 'state': 101, 'major': 102, 'quantum': 103, 'video': 104, 'game': 105, 'access': 106, 'related': 107, 'model': 108, 'services': 109, 'World': 110, 'modern': 111, 'police': 112, 'concept': 113, 'without': 114, 'there': 115, 'users': 116, 'since': 117, 'American': 118, 'service': 119, 'commonly': 120, 'referred': 121, 'field': 122, 'several': 123, 'million': 124, 'image': 125, 'network': 126, 'after': 127, 'analysis': 128, 'features': 129, 'technology': 130, 'product': 131, 'those': 132, 'example,': 133, 'sometimes': 134, 'neural': 135, 'range': 136, 'early': 137, 'population': 138, 'provide': 139, 'multiple': 140, 'single': 141, 'Internet': 142, 'standard': 143, 'engineering': 144, 'academic': 145, 'statistical': 146, 'support': 147, 'like': 148, 'during': 149, 'knowledge': 150, 'then': 151, 'Data': 152, 'theory': 153, 'management': 154, 'forms': 155, 'written': 156, 'provides': 157, 'work': 158, 'operating': 159, 'media': 160, 'languages': 161, 'become': 162, 'source': 163, 'Python': 164, 'movement': 165, 'rights': 166, 'virtual': 167, 'particular': 168, 'became': 169, 'against': 170, 'experience': 171, 'Amazon': 172, 'digital': 173, 'defined': 174, 'century,': 175, 'take': 176, 'free': 177, 'among': 178, 'would': 179, 'There': 180, 'large': 181, '(such': 182, 'created': 183, 'learning,': 184, 'political': 185, 'data.': 186, 'includes': 187, 'what': 188, 'These': 189, 'processing': 190, 'cloud': 191, 'algorithms': 192, 'individual': 193, 'released': 194, 'types': 195, 'company': 196, 'networks': 197, 'platform': 198, 'area': 199, 'three': 200, 'UNKNOWN': 201, 'PAD': 0}

In [80]:
with open('word2idx.json','w') as w:
    json.dump(Word2Idx,w)
with open('idx2word.json','w') as w:
    json.dump(Idx2Word,w)

In [93]:
w2idx_db = descriptions_db.copy()

In [103]:
w2idx_dict = {}
for index,r in w2idx_db.iterrows():
    processed = r['description'].translate ({ord(c): " " for c in "''!@#$%^&*()[]{};:,./<>?\|`~-=_+"})
    list_doc = processed.split(' ')
    w2i_list = []
    for element in list_doc:
        if element in Word2Idx:
             w2i_list.append(Word2Idx[element])
        else: 
            w2i_list.append(Word2Idx['UNKNOWN'])
    while len(w2i_list) < 100:
       w2i_list.append(Word2Idx['PAD'])
    if len(w2i_list) > 100:
        w2i_list = w2i_list[:100]
    w2idx_dict[r['ID']] = w2i_list

In [106]:
for key in w2idx_dict.keys():
    if len(w2idx_dict[key]) >= 100:
        print(key,w2idx_dict[key], len(w2idx_dict[key]))

201, 201, 190, 201, 201, 201, 201, 201, 201, 201] 100
722 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 4, 16, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 59, 201, 201, 201, 201, 201, 201, 201, 201, 201, 16, 201, 9, 13, 201, 25, 201, 201, 201, 33, 16, 201, 201, 201, 16, 201, 201, 16, 201, 201, 68, 201, 201, 96, 201, 201, 201, 201, 7, 201, 2, 201, 201, 201, 201, 201, 201, 201, 109, 58, 88, 201, 15, 201, 201, 201, 201, 52, 201, 9, 13, 201, 201, 201, 201, 16, 51, 201, 201, 201, 201] 100
723 [201, 201, 201, 3, 201, 201, 201, 170, 201, 201, 201, 201, 201, 8, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 15, 201, 201, 201, 201, 201, 201, 201, 201, 201, 8, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 201, 201, 201, 201, 136, 201, 8, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
724 [201, 201, 201, 201, 201, 201, 95, 201, 201, 201, 201, 23, 201, 201, 201, 201, 201, 201, 126, 201, 201, 201, 201, 183, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 163, 201, 201, 201, 95, 201, 56, 201, 201, 201, 106, 201, 201, 44, 201, 201, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
725 [201, 201, 201, 201, 201, 201, 201, 201, 201, 134, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 164, 42, 38, 201, 201, 147, 201, 181, 201, 201, 201, 201, 201, 201, 201, 201, 2, 201, 181, 201, 201, 201, 201, 201, 201, 201, 201, 201, 52, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 183, 201, 201, 201, 2, 201, 3, 123, 8, 201, 201, 201, 201, 201, 201, 201, 183, 201, 201, 201, 129, 201, 201, 201, 201, 26, 201, 201, 2, 201, 201, 201, 201, 201, 201, 163, 20, 201, 201] 100
726 [201, 23, 42, 201, 201, 201, 201, 20, 201, 156, 201, 201, 164, 42, 38, 201, 6, 201, 201, 128, 201, 201, 168, 201, 201, 201, 6, 201, 201, 201, 201, 201, 201, 201, 201, 45, 87, 201, 201, 201, 177, 20, 194, 97, 201, 200, 201, 201, 201, 201, 201, 201, 201, 201, 3, 201, 43, 201, 201, 201, 201, 201, 43, 201, 6, 201, 1, 27, 201, 50, 140, 45, 201, 201, 201, 76, 201, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
727 [201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
728 [201, 201, 42, 201, 201, 201, 201, 201, 42, 201, 60, 201, 201, 113, 201, 201, 201, 4, 201, 201, 6, 201, 201, 201, 46, 201, 201, 201, 18, 44, 201, 201, 201, 201, 201, 201, 201, 90, 201, 201, 201, 46, 201, 201, 201, 18, 44, 201, 91, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 1, 201, 106, 201, 18, 201, 201, 6, 201, 201, 201, 201, 2, 4, 34, 201, 201, 201, 201, 9, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 23, 201, 201, 201, 201, 201, 201, 201, 201] 100
729 [201, 39, 201, 158, 2, 201, 201, 201, 201, 201, 145, 201, 201, 2, 201, 201, 201, 201, 201, 201, 145, 201, 201, 201, 92, 201, 201, 201, 201, 145, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 14, 145, 201, 201, 201, 145, 39, 37, 201, 201, 201, 201, 201, 14, 201, 145, 201, 25, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 37, 39, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 145, 201, 201, 201, 201, 201, 201, 201, 201, 201, 56, 201, 201, 201, 16, 201, 201, 201] 100
730 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 79, 201, 54, 79, 201, 23, 79, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 11, 201, 201, 201, 201, 36, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 13, 201, 201, 201, 201, 79, 201, 66, 201, 201, 201, 201, 201, 201, 201, 201, 54, 79, 201, 23, 79, 201, 201, 201, 201, 201, 201, 201, 201, 201, 115, 201, 201, 201, 56, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
731 [201, 201, 201, 201, 201, 198, 201, 201, 119, 201, 201, 201, 201, 1, 201, 201, 201, 201, 201, 201, 20, 201, 201, 41, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 14, 201, 20, 201, 201, 201, 201, 201, 201, 34, 201, 201, 2, 77, 8, 25, 62, 174, 201, 201, 201, 201, 201, 201, 201, 201, 141, 159, 29, 201, 201, 201, 201, 201, 201, 30, 167, 201, 201, 119, 201, 68, 177, 201, 201, 201, 201, 201, 20, 1, 201, 201, 201, 201, 41, 201, 201, 201, 201, 201, 47, 201, 201, 201, 201, 201] 100
732 [201, 201, 201, 201, 201, 198, 201, 201, 119, 201, 201, 201, 201, 1, 201, 201, 201, 201, 201, 201, 20, 201, 201, 41, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 14, 201, 20, 201, 201, 201, 201, 201, 201, 34, 201, 201, 2, 77, 8, 25, 62, 174, 201, 201, 201, 201, 201, 201, 201, 201, 141, 159, 29, 201, 201, 201, 201, 201, 201, 30, 167, 201, 201, 119, 201, 68, 177, 201, 201, 201, 201, 201, 20, 1, 201, 201, 201, 201, 41, 201, 201, 201, 201, 201, 47, 201, 201, 201, 201, 201] 100
733 [152, 201, 201, 201, 54, 201, 85, 201, 201, 1, 201, 201, 25, 201, 201, 201, 201, 11, 201, 201, 201, 6, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 55, 201, 201, 11, 201, 201, 201, 201, 66, 201, 201, 201, 201, 201, 6, 201, 201, 201, 141, 201, 201, 201, 141, 201, 201, 201, 201, 201, 201, 201, 201, 18, 10, 201, 201, 52, 201, 9, 201, 201, 201, 201, 22, 201, 201, 201, 6, 201, 134, 201, 201, 201, 201, 26, 54, 65, 201, 201, 201, 201, 201, 201, 201, 201, 128, 201, 201, 145] 100
734 [201, 201, 201, 101, 201, 53, 201, 4, 201, 32, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 22, 201, 201, 201, 201, 201, 174, 201, 201, 201, 8, 201, 201, 201, 201, 1, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 69, 201, 1, 201, 201, 201, 201, 201, 111, 201, 3, 14, 201, 201, 201, 201, 17, 201, 201, 201, 201, 201, 201, 201, 201, 201, 4, 201, 201, 201, 201, 201, 201, 22, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
735 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 4, 201, 201, 10, 201, 201, 201, 201, 201, 201, 201, 42, 38, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 38, 201, 201, 201, 201, 201, 201, 1, 201, 201, 201, 201, 201, 201, 201, 201, 38, 1, 201, 201, 201, 2, 201, 201, 201, 201, 50, 140, 201, 201, 201, 156, 201, 201, 201, 201, 201, 201, 201, 201, 201, 45, 201, 201, 45, 201, 201, 45, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
736 [201, 201, 201, 201, 163, 201, 201, 1, 201, 201, 201, 201, 164, 201, 201, 26, 201, 72, 90, 31, 201, 201, 201, 201, 201, 164, 201, 201, 201, 201, 201, 136, 201, 201, 201, 201, 164, 90, 201, 201, 201, 201, 201, 18, 2, 64, 201, 90, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 117, 13, 97, 201, 39, 201, 201, 201, 201, 201, 201, 201, 201, 2, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 2, 147, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
737 [201, 201, 201, 201, 23, 201, 1, 201, 23, 90, 156, 201, 201, 42, 38, 201, 201, 163, 38, 201, 26, 201, 38, 201, 201, 201, 38, 201, 201, 201, 201, 201, 201, 201, 10, 201, 201, 1, 201, 163, 90, 3, 201, 201, 201, 42, 38, 201, 201, 201, 201, 38, 201, 201, 201, 201, 201, 201, 38, 201, 201, 90, 201, 201, 72, 90, 201, 201, 201, 201, 201, 201, 201, 201, 115, 201, 17, 33, 195, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 23, 201, 201, 201, 159, 29, 201, 33, 3, 201] 100
738 [152, 128, 201, 201, 51, 201, 201, 201, 201, 201, 201, 201, 201, 6, 2, 201, 201, 201, 201, 201, 54, 201, 201, 201, 201, 201, 201, 201, 201, 152, 128, 201, 140, 201, 201, 201, 201, 201, 201, 201, 97, 201, 201, 201, 201, 201, 201, 201, 10, 201, 33, 88, 201, 79, 201, 201, 15, 79, 201, 201, 201, 201, 201, 88, 100, 201, 6, 128, 201, 201, 201, 201, 201, 201, 11, 201, 201, 201, 201, 201, 11, 201, 152, 201, 201, 201, 168, 6, 128, 201, 1, 201, 201, 146, 201, 201, 150, 201, 201, 201] 100
739 [201, 201, 201, 201, 201, 201, 201, 164, 42, 38, 201, 201, 201, 201, 201, 201, 201, 201, 157, 201, 201, 201, 201, 201, 201, 201, 26, 70, 31, 201, 201, 201, 201, 148, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 180, 201, 7, 201, 201, 201, 201, 60, 201, 201, 101, 72, 201, 148, 201, 201, 201, 201, 201, 201, 201, 1, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 156, 201, 201, 201, 201, 201, 201, 117, 151, 201, 201, 201, 201, 39, 201, 201, 201] 100
740 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 12, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 101, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 21, 201, 102, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 138, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 9] 100
741 [201, 201, 201, 201, 201, 201, 201, 35, 78, 174, 201, 201, 199, 201, 201, 101, 201, 201, 201, 201, 201, 201, 36, 201, 201, 201, 201, 201, 101, 201, 201, 201, 201, 201, 201, 201, 101, 201, 201, 201, 201, 201, 201, 201, 201, 201, 101, 201, 201, 201, 201, 201, 201, 201, 201, 11, 201, 201, 201, 30, 1, 201, 201, 201, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
742 [201, 201, 201, 35, 78, 201, 201, 117, 201, 201, 201, 201, 65, 99, 201, 48, 201, 201, 201, 201, 201, 201, 201, 166, 66, 52, 76, 166, 48, 201, 201, 8, 201, 201, 201, 201, 201, 201, 201, 99, 201, 201, 201, 201, 201, 201, 201, 201, 92, 201, 201, 201, 201, 166, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 118, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 48, 18, 201, 201, 201, 201, 201, 8, 155, 201, 201, 60, 201, 201, 118, 201, 201, 201] 100
743 [201, 74, 201, 201, 201, 201, 106, 201, 201, 201, 201, 201, 201, 201, 106, 3, 201, 201, 201, 201, 23, 26, 1, 201, 201, 114, 201, 201, 201, 201, 159, 29, 201, 36, 201, 201, 201, 201, 201, 201, 201, 201, 4, 201, 201, 201, 201, 201, 201, 23, 201, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
744 [201, 201, 201, 201, 201, 201, 20, 59, 201, 201, 201, 201, 201, 201, 131, 201, 201, 201, 201, 201, 201, 201, 198, 201, 201, 119, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 8, 201, 139, 40, 198, 25, 33, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 198, 201, 201, 20, 201, 201, 119, 201, 201, 201, 201, 201, 201, 198, 201, 201, 201, 201, 119, 201, 201, 201, 201, 82, 201, 201, 201] 100
745 [201, 201, 201, 141, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 1, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 141, 69, 201, 201, 201, 201, 201, 201, 201, 201, 167, 201, 31, 201, 201, 201, 201, 201, 201, 201, 201, 201, 33, 167, 201, 201, 33, 167, 201, 201, 201, 201, 201, 126, 201, 201, 201, 201, 69, 201, 72, 201, 201, 201, 201, 33, 167, 201, 201, 201, 201, 201, 201, 167, 201, 201, 201, 201, 141, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
746 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 57, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 44, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 2, 201, 201, 201, 201, 201, 201] 100
747 [201, 201, 201, 201, 7, 126, 201, 201, 201, 201, 201, 201, 201, 126, 201, 113, 1, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 126, 201, 201, 26, 201, 201, 1, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 109, 201, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 201, 201, 5, 201, 132, 10, 201, 201, 201, 201, 201, 201, 126, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 11, 167, 201, 201, 33, 20, 201, 201, 201, 201, 201, 201, 143, 201, 201, 201, 201, 201, 201, 201] 100
748 [201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
749 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 68, 201, 201, 201, 201, 201, 201, 201, 201, 201, 124, 201, 201, 201, 201, 201, 124, 201, 201, 201, 201, 2, 50, 201, 124, 61, 201, 201, 201, 201, 100, 201, 201, 201, 201, 201, 199, 201, 201, 201, 12, 201, 201, 201, 201, 201, 201, 201, 201, 201, 12, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
750 [201, 94, 201, 13, 174, 201, 201, 79, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 25, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 93, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 94, 201, 201, 138, 201, 201, 201, 201, 201, 201, 201, 201, 201, 93, 94, 201, 201, 93, 201, 201, 201, 201, 201, 201, 201, 201, 61, 201, 201, 181, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 123, 201, 201, 201, 113, 201, 94, 201, 26] 100
751 [201, 128, 201, 7, 44, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 96, 38, 190, 201, 201, 128, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 71, 201, 201, 201, 201, 54, 201, 201, 128, 201, 201, 201, 201, 201, 201, 201, 201, 201, 5, 201, 201, 201, 201, 201, 201, 201, 201, 15, 160, 201, 201, 201, 201, 201, 70, 1, 136, 3, 201, 201, 201, 119, 201, 201, 201, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
752 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 10, 201, 201, 201, 201, 6, 128, 201, 88, 54, 201, 201, 201, 139, 201, 201, 201, 201, 201, 201, 201, 201, 88, 201, 201, 201, 201, 201, 88, 201, 201, 27, 201, 201, 201, 201, 190, 201, 201, 201, 6, 201, 201, 51, 201, 201, 201, 201, 190, 201, 88, 201, 154, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 181, 201, 201, 201, 201, 134, 201, 6, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 88] 100
753 [201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 87, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 86, 201, 201, 201, 86, 201, 201, 201, 58, 201, 201, 201, 201, 201, 201, 201, 201, 201, 32, 46, 201, 201, 12, 201, 201, 201, 201, 201, 201, 201, 201, 2, 201, 201, 201, 14, 201, 201, 201, 201, 201, 201, 201, 201, 201, 136, 3, 201, 5, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
754 [201, 201, 201, 201, 118, 144, 201, 201, 16, 196, 201, 201, 201, 201, 201, 201, 201, 3, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 196, 201, 201, 201, 201, 201, 122, 201, 201, 201, 201, 201, 201, 201, 201, 12, 201, 201, 201, 201, 201, 201, 201, 201, 44, 201, 201, 39, 201, 201, 87, 201, 201, 201, 67, 201, 201, 19, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 189, 201, 201, 201, 12, 201, 201] 100
755 [36, 201, 201, 201, 201, 172, 201, 201, 201, 4, 201, 201, 201, 201, 191, 74, 109, 1, 201, 201, 201, 201, 201, 74, 198, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
756 [201, 74, 201, 201, 201, 201, 201, 201, 23, 29, 201, 201, 201, 6, 201, 201, 191, 201, 201, 201, 74, 201, 201, 114, 201, 201, 154, 201, 201, 84, 201, 201, 43, 201, 201, 10, 201, 201, 6, 201, 201, 201, 17, 116, 50, 201, 142, 201, 201, 201, 201, 201, 201, 201, 18, 9, 201, 201, 50, 140, 201, 3, 201, 201, 201, 201, 201, 201, 201, 201, 84, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 141, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 17] 100
757 [201, 6, 108, 201, 201, 201, 201, 201, 201, 201, 108, 1, 201, 201, 201, 6, 201, 201, 201, 34, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 100, 201, 201, 201, 201, 201, 201, 6, 108, 201, 201, 1, 201, 6, 201, 201, 201, 201, 201, 201, 201, 201, 98, 201, 8, 201, 4, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 43, 6, 108, 201, 201, 201, 201, 201, 201, 201, 107, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201] 100
758 [201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100
759 [201, 201, 201, 201, 201, 128, 201, 6, 201, 201, 201, 201, 201, 10, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 6, 201, 201, 7, 201, 201, 6, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 2, 201, 54, 201, 201, 201, 201, 201, 201, 81, 201, 201, 201, 23, 42, 201, 201, 56, 201, 201, 201, 201, 201, 201, 201, 201, 88, 6, 201, 201, 201, 201, 201, 201, 201, 88, 201, 201, 201, 201, 201, 58, 201, 27, 201, 201, 201, 201, 201, 201, 201, 201, 154, 201] 100
760 [201, 74, 201, 201, 6, 201, 201, 201, 201, 201, 201, 201, 7, 44, 201, 201, 201, 6, 201, 201, 201, 201, 201, 201, 201, 29, 10, 201, 201, 201, 6, 128, 201, 201, 201, 83, 201, 201, 201, 201, 88, 201, 201, 201, 201, 201, 201, 201, 201, 6, 3, 201, 201, 11, 201, 201, 201, 201, 201, 201, 201, 201, 6, 201, 201, 141, 201, 1, 201, 10, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 6, 201, 201, 201, 201, 201, 201, 3, 201, 201, 49, 201, 5, 201, 201, 201, 201, 201, 201, 201] 100
761 [95, 201, 201, 201, 201, 201, 201, 201, 57, 201, 201, 177, 201, 201, 60, 20, 201, 201, 201, 201, 95, 58, 201, 95, 201, 119, 201, 201, 119, 7, 187, 95, 201, 201, 95, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 95, 201, 201, 201, 201, 201, 201, 81, 201, 67, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 81, 201, 95, 201, 201, 201, 201, 201, 201, 201, 2, 201, 201, 201, 201, 201, 201, 201, 116, 201, 201, 201, 201, 201, 201, 66, 201, 2, 8, 116, 201] 100
762 [95, 201, 201, 201, 201, 201, 81, 42, 201, 201, 201, 201, 59, 201, 95, 4, 201, 201, 2, 95, 201, 201, 14, 201, 201, 8, 109, 201, 201, 201, 52, 27, 201, 201, 201, 201, 201, 201, 95, 201, 201, 201, 201, 201, 201, 201, 52, 201, 201, 176, 201, 201, 201, 201, 201, 201, 201, 201, 201, 109, 201, 201, 139, 201, 148, 201, 201, 72, 37, 201, 201, 119, 201, 201, 201, 201, 201, 201, 106, 201, 84, 6, 201, 65, 201, 201, 201, 201, 6, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 95] 100
763 [201, 201, 201, 119, 201, 201, 201, 201, 201, 7, 44, 201, 201, 201, 201, 201, 201, 201, 20, 201, 201, 201, 108, 201, 4, 20, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 134, 121, 201, 201, 201, 201, 201, 201, 201, 201, 201, 121, 201, 201, 201, 201, 201, 201, 201, 201, 70, 201, 7, 44, 201, 201, 60, 20, 201, 201, 201, 20, 201, 201, 20, 201, 201, 43, 201, 201, 201, 201, 201, 201, 201, 201, 83, 201, 201, 57, 201, 201, 201, 201, 191, 74, 201, 201, 2, 201, 201] 100
764 [201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100